server:
  port: 8082
  servlet:
    context-path: /profile

spring:
  application:
    name: profile-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/food_delivery_profile
    username: root
    password: secret
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    database: postgresql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/