export const QUERIES_KEY = {
  AUTH: {
    SIGN_IN: 'SIGN_IN_USER',
    SIGN_UP: 'SIGN_UP_USER',
    SEND_OTP: 'SEND_OTP',
    VERIFICATION_EMAIL: 'VERIFICATION_EMAIL',
    RESET_PASSWORD: 'RESET_PASSWORD',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    GOOGLE_SIGN_IN: 'GOOGLE_SIGN_IN'
  },
  USER: {}
};
