server:
  port: 8083
  servlet:
    context-path: /notification

spring:
  data:
    mongodb:
      uri: mongodb://root:secret@localhost:27017/notification-service?authSource=admin
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: otp-group, reset-password-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'

email-service:
  apiKey: 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
  url: https://api.brevo.com
  senderName: Food Delivery
  senderEmail: truongbn.dev@gmail.com
  clientUrl: http://localhost:3000