server:
  port: 8082
  servlet:
    context-path: /restaurant

spring:
  data:
    mongodb:
      username: root
      password: secret
      host: localhost
      port: 27017
      database: food_delivery_identity
      authentication-database: admin